import json

# Load the original games.json
json_path = 'database/senior_python/games.json'
with open(json_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Define the enriched stories for each of the 12 stations

stories = {
    1: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>Introduction to Python</li>"
        "<li>Python for AI and Machine Learning</li>"
        "<li>How to Start & Install Python</li>"
        "<li>The <code>print()</code> Function</li>"
        "<li>Variables in Python & Naming Rules</li>"
        "</ul>"
        "<hr>"
        "<h3>📘 What is Python?</h3>"
        "Python is a simple, most popular, object-oriented, interpreted, and high-level programming language."
        "<h3>🌟 Why Python?</h3>"
        "<ol>"
        "<li><b>Simple and Easy to Learn:</b> Writing Python code feels just like reading plain English!</li>"
        "<li><b>Free and Open Source:</b> Allows the global developer community to build, improve, and share software freely.</li>"
        "<li><b>Interpreted:</b> You write code and execute it directly line-by-line. This feature helps programmers debug code instantly!</li>"
        "<li><b>Object-Oriented & Procedure-Oriented:</b> Built around the concept of reusable code blocks, functions, and objects.</li>"
        "<li><b>Extensive Standard Library:</b> Packed with massive built-in utility modules for various tasks.</li>"
        "</ol>"
        "<h3>💼 Where is Python Used?</h3>"
        "<ul>"
        "<li><b>Web Scraping:</b> Using automated bots to extract content and raw data from websites.</li>"
        "<li><b>Machine Learning & AI:</b> Training models to think like humans using massive datasets and complex algorithms.</li>"
        "<li><b>Game Development:</b> Creating interactive 2D and 3D games.</li>"
        "<li><b>Automation:</b> Converting manual, repetitive tasks into automatic, fast processes.</li>"
        "<li><b>Ethical Hacking:</b> Automating vulnerability scanning, network requests, and system tests.</li>"
        "<li><b>Web Development:</b> Backend servers for world-famous apps like Instagram, Spotify, YouTube, Pinterest, and Dropbox!</li>"
        "</ul>"
        "<h3>🤖 Why Python is Best for AI & ML</h3>"
        "It can run on a variety of hardware platforms or software architectures, has a beginner-friendly syntax, and is supported by a massive community (like the Python Discord community)."
        "<h3>📥 How to Install Python</h3>"
        "Visit the official website: <a href='https://www.python.org/downloads/' target='_blank'>python.org/downloads</a> to download and install the latest version."
        "<h3>🔊 The <code>print()</code> Function</h3>"
        "The <code>print()</code> function is Python's voice! It prints any specified message or value to the screen or other standard output devices.<br>"
        "<b>Example:</b><br>"
        "<code>print(\"Hello World!\")</code>"
        "<h3>📦 Variables in Python</h3>"
        "Variables are named containers used for storing data values. In Python, variables do not need to be declared with any particular type, and they can dynamically change types even after they are set."
        "<h3>💡 Rules for Naming Variables:</h3>"
        "<ol>"
        "<li>Must start with a letter or underscore only (e.g., <code>name1</code>, not <code>1name</code>).</li>"
        "<li>Do not use reserved programming keywords (e.g., <code>int</code>, <code>if</code>, <code>for</code>, <code>print</code>).</li>"
        "<li>Use descriptive and suitable names instead of single letters (e.g., <code>length</code> or <code>age</code>, not <code>x</code> or <code>y</code>).</li>"
        "<li>Use Camel Case (e.g., <code>firstName</code>) or Pascal Case (e.g., <code>FirstName</code>) for multiple words.</li>"
        "<li>Python is case-sensitive (e.g., <code>name</code> is completely different from <code>Name</code>).</li>"
        "<li>Concatenate variables with text strings using the plus sign (<code>+</code>).</li>"
        "</ol>"
    ),
    2: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>Variables in Python</li>"
        "<li>Data Naming Rules & Conventions</li>"
        "<li>Parentheses, Brackets, and Braces</li>"
        "<li>Python Data Types & the <code>type()</code> Function</li>"
        "<li>The <code>input()</code> Function</li>"
        "<li>Lists (Arrays) and List Operations</li>"
        "</ul>"
        "<hr>"
        "<h3>📦 Variables in Python</h3>"
        "Variables are named containers used for storing data values. In Python, variables do not need to be declared with any particular type, and they can dynamically change types even after they are set."
        "<h3>💡 Rules for Naming Variables:</h3>"
        "<ol>"
        "<li>Must start with a letter or underscore only (e.g., <code>name1</code>, not <code>1name</code>).</li>"
        "<li>Do not use reserved programming keywords (e.g., <code>int</code>, <code>if</code>, <code>for</code>, <code>print</code>).</li>"
        "<li>Use descriptive and suitable names instead of single letters (e.g., <code>length</code> or <code>age</code>, not <code>x</code> or <code>y</code>).</li>"
        "<li>Use Camel Case (e.g., <code>firstName</code>) or Pascal Case (e.g., <code>FirstName</code>) for multiple words.</li>"
        "<li>Python is case-sensitive (e.g., <code>name</code> is completely different from <code>Name</code>).</li>"
        "<li>Concatenate variables with text strings using the plus sign (<code>+</code>).</li>"
        "</ol>"
        "<h3>🔑 Using Parentheses, Brackets & Braces:</h3>"
        "<ul>"
        "<li><b>Circular Parentheses <code>()</code>:</b> Used to call functions and supply additional parameters or arguments.</li>"
        "<li><b>Square Brackets <code>[]</code>:</b> Used to define, declare, and index items in a List.</li>"
        "<li><b>Curly Brackets <code>{}</code>:</b> Used to define Dictionaries (Key-Value maps) and insert replacements.</li>"
        "</ul>"
        "<h3>🧪 Python Built-in Data Types</h3>"
        "Variables can store data of different types, which serve different purposes. The primary categories are:"
        "<ul>"
        "<li><b>Text Type:</b> <code>str</code></li>"
        "<li><b>Numeric Types:</b> <code>int</code>, <code>float</code>, <code>complex</code></li>"
        "<li><b>Sequence Types:</b> <code>list</code>, <code>tuple</code>, <code>range</code></li>"
        "<li><b>Mapping Type:</b> <code>dict</code></li>"
        "<li><b>Boolean Type:</b> <code>bool</code> (True/False)</li>"
        "<li><b>None Type:</b> <code>NoneType</code></li>"
        "<li><i>How to check?</i> Use the <code>type()</code> function! (e.g., <code>print(type(5))</code> yields <code>&lt;class 'int'&gt;</code>).</li>"
        "</ul>"
        "<h3>📥 The <code>input()</code> Function</h3>"
        "The <code>input()</code> function allows the program to accept user inputs from the terminal. <i>Note:</i> User inputs are always received as text strings (<code>str</code>). If you want to perform math, you MUST convert it to a number using <code>int()</code> or <code>float()</code>."
        "<h3>🎒 Magic Lists (Lists)</h3>"
        "Lists are used to store multiple items in a single variable. List items are indexed, starting with index <code>[0]</code>, then <code>[1]</code>, and so on."
        "<h3>🛠️ Common List Operations:</h3>"
        "<ul>"
        "<li><b>Access/Print list element:</b> <code>print(my_list[0])</code></li>"
        "<li><b>Change value:</b> <code>my_list[1] = 10</code></li>"
        "<li><b>Add to end:</b> <code>my_list.append(value)</code></li>"
        "<li><b>Insert at specific index:</b> <code>my_list.insert(index, value)</code></li>"
        "<li><b>Add another list:</b> <code>my_list.extend(another_list)</code></li>"
        "<li><b>Sort ascending:</b> <code>my_list.sort()</code></li>"
        "<li><b>Sort descending:</b> <code>my_list.sort(reverse=True)</code></li>"
        "<li><b>Delete elements:</b> <code>my_list.remove(value)</code> or empty the whole list with <code>my_list.clear()</code></li>"
        "</ul>"
    ),
    3: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>Operators in Python</li>"
        "<li>Numeric Types & Type Conversions</li>"
        "<li>String indexing & Lists of Characters</li>"
        "<li>String Functions & Operations</li>"
        "</ul>"
        "<hr>"
        "<h3>➕ Operators in Python</h3>"
        "Operators are magic symbols used to perform mathematical and logical operations on variables and values."
        "<ul>"
        "<li><b>Arithmetic Operators:</b> Used for mathematical calculations:<br>"
        "<code>+</code> (Addition), <code>-</code> (Subtraction), <code>*</code> (Multiplication), <code>/</code> (Division), <code>%</code> (Modulus - remainder of division), <code>**</code> (Exponentiation - power), <code>//</code> (Floor Division - division rounded down).</li>"
        "<li><b>Assignment Operators:</b> Used to assign values to variables:<br>"
        "<code>=</code> (Assign), <code>+=</code> (Add and assign), <code>-=</code> (Subtract and assign), <code>*=</code> (Multiply and assign), <code>/=</code> (Divide and assign).</li>"
        "<li><b>Comparison Operators:</b> Used to compare two values, returning a Boolean (True/False):<br>"
        "<code>==</code> (Equal to), <code>!=</code> (Not equal to), <code>&gt;</code> (Greater than), <code>&lt;</code> (Less than), <code>&gt;=</code> (Greater than or equal to), <code>&lt;=</code> (Less than or equal to).</li>"
        "<li><b>Logical Operators:</b> Used to combine conditional statements:<br>"
        "<code>and</code> (returns True if BOTH conditions are true), <code>or</code> (returns True if AT LEAST ONE condition is true), <code>not</code> (reverses the boolean result).</li>"
        "</ul>"
        "<h3>🧪 Numeric Types & Type Conversions</h3>"
        "Python supports three numeric types: <code>int</code> (integers like 5), <code>float</code> (decimals like 5.5), and <code>complex</code> (complex numbers like 3+5j). You can easily convert between types using:"
        "<ul>"
        "<li><code>int()</code>: Converts a value to an integer (e.g., <code>int(5.9)</code> becomes <code>5</code>).</li>"
        "<li><code>float()</code>: Converts a value to a decimal (e.g., <code>float(5)</code> becomes <code>5.0</code>).</li>"
        "<li><code>complex()</code>: Converts a value to complex (e.g., <code>complex(5)</code> becomes <code>5+0j</code>).</li>"
        "</ul>"
        "<h3>🔤 Strings & Indexing</h3>"
        "A string is a sequence of characters enclosed in quotation marks. In Python, spaces are included and counted as characters! Strings are treated like a read-only list of characters. You can access individual characters using square brackets starting from index <code>[0]</code>.<br>"
        "<b>Example:</b><br>"
        "<code>word = \"Python\"</code><br>"
        "<code>print(word[0])</code> prints <code>P</code><br>"
        "<code>print(word[2])</code> prints <code>t</code>"
        "<h3>⚙️ String Functions</h3>"
        "A function is a reusable, organized block of code that performs a specific action. You can use string methods to manipulate text (e.g., <code>upper()</code>, <code>lower()</code>, <code>len()</code> to get string length, and concatenation with <code>+</code>)."
    ),
    4: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>Tuples (Ordered & Unchangeable collections)</li>"
        "<li>Tuple Properties, Indexing & Operations</li>"
        "<li>How to Modify a Tuple (Workaround)</li>"
        "<li>Dictionaries (Key-Value Pairs)</li>"
        "<li>Dictionary Properties, Accessing, Updating & Deleting</li>"
        "<li>Master Comparison between Lists, Tuples, and Dictionaries</li>"
        "</ul>"
        "<hr>"
        "<h3>🔒 Tuples in Python</h3>"
        "A tuple is a built-in data type used to store multiple items in a single variable. A tuple is **ordered** and **unchangeable (immutable)**. Tuples are written with circular parentheses <code>()</code>."
        "<h3>💡 Properties of Tuples:</h3>"
        "<ul>"
        "<li><b>Ordered:</b> The items have a defined order that will not change.</li>"
        "<li><b>Unchangeable:</b> You cannot add, modify, or remove items once the tuple is created.</li>"
        "<li><b>Allow Duplicates:</b> Items can repeat since they are accessed via unique index coordinates.</li>"
        "</ul>"
        "<h3>🛠️ Accessing and Modifying Tuples:</h3>"
        "<ul>"
        "<li><b>Accessing:</b> Use index brackets (e.g., <code>fruits[0]</code> fetches the first item).</li>"
        "<li><b>Changing Tuple Items (Workaround):</b> Because tuples are unchangeable, to edit them you must:<br>"
        "1. Convert the tuple to a list: <code>my_list = list(my_tuple)</code><br>"
        "2. Modify/add items in the list: <code>my_list.append(\"cherry\")</code><br>"
        "3. Convert it back to a tuple: <code>my_tuple = tuple(my_list)</code></li>"
        "<li><b>Tuple Methods:</b> <code>count()</code> (returns the number of times a value appears) and <code>index()</code> (searches for a value and returns its position).</li>"
        "</ul>"
        "<h3>📖 Dictionaries in Python</h3>"
        "Dictionaries are used to store data values in **key:value** pairs. They are **ordered** (starting in Python 3.7), **changeable**, and **do not allow duplicate keys**. Dictionaries are written with curly brackets <code>{}</code>."
        "<h3>🛠️ Dictionary Operations:</h3>"
        "<ul>"
        "<li><b>Creating:</b> <code>car = {\"brand\": \"Ford\", \"model\": \"Mustang\", \"year\": 1964}</code></li>"
        "<li><b>Accessing:</b> Get a value by specifying its key in square brackets (e.g., <code>car[\"model\"]</code>) or using the <code>get()</code> function.</li>"
        "<li><b>Updating/Modifying:</b> Directly change a key's value (e.g., <code>car[\"year\"] = 2020</code>) or use the <code>update()</code> method.</li>"
        "<li><b>Removing Items:</b> Use <code>pop(key)</code> to delete a specific item, <code>popitem()</code> to remove the last inserted item, or <code>clear()</code> to empty the dictionary.</li>"
        "<li><b>Useful Methods:</b> <code>keys()</code> (returns list of all keys), <code>values()</code> (returns list of all values), and <code>items()</code> (returns list of key-value tuples).</li>"
        "</ul>"
        "<h3>⚖️ Complete Data Collection Comparison:</h3>"
        "<table border='1' cellpadding='5' style='border-collapse: collapse; text-align: left; width: 100%;'>"
        "<tr><th>Collection Type</th><th>Syntax</th><th>Ordered</th><th>Changeable</th><th>Allows Duplicates</th></tr>"
        "<tr><td><b>List</b></td><td><code>[]</code></td><td>Yes</td><td>Yes</td><td>Yes</td></tr>"
        "<tr><td><b>Tuple</b></td><td><code>()</code></td><td>Yes</td><td>No (Read-only)</td><td>Yes</td></tr>"
        "<tr><td><b>Dictionary</b></td><td><code>{Key:Value}</code></td><td>Yes</td><td>Yes</td><td>No (Unique keys)</td></tr>"
        "</table>"
    ),
    5: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>If / Elif / Else Statements</li>"
        "<li>Standard & Short Hand Conditional Syntax</li>"
        "<li>While Loops (Executing code under a condition)</li>"
        "<li>Essential While Loop Requirements</li>"
        "<li>Loop Control Statements: Break, Continue, and Else</li>"
        "</ul>"
        "<hr>"
        "<h3>🚦 If Conditions & Decisions</h3>"
        "Python supports the usual logical conditions from mathematics: <code>a == b</code>, <code>a != b</code>, <code>a &lt; b</code>, <code>a &lt;= b</code>, <code>a &gt; b</code>, <code>a &gt;= b</code>."
        "<ul>"
        "<li><b>if:</b> Executes a block of code if the condition is True.</li>"
        "<li><b>elif:</b> Short for 'else if'. Checks this condition if the previous conditions were False.</li>"
        "<li><b>else:</b> Catches anything which wasn't caught by the preceding conditions.</li>"
        "<li><b>Short Hand If:</b> If you have only one statement to execute:<br><code>if a &gt; b: print(\"a is greater than b\")</code></li>"
        "<li><b>Short Hand If...Else (Ternary Operator):</b> Put both on a single line:<br><code>print(\"A\") if a &gt; b else print(\"B\")</code></li>"
        "</ul>"
        "<h3>🔄 While Loops</h3>"
        "A While Loop executes a set of statements as long as a target condition remains true."
        "<h3>⚠️ Three Essential Rules for While Loops:</h3>"
        "<ol>"
        "<li><b>Initializer Variable:</b> Set up your counter or condition checker before the loop starts (e.g., <code>i = 1</code>).</li>"
        "<li><b>Loop Condition:</b> Set up the boundary condition (e.g., <code>while i &lt; 6:</code>).</li>"
        "<li><b>Increment/Update:</b> **CRITICAL!** You must update or increment the counter variable inside the loop body (e.g., <code>i += 1</code>). Otherwise, the loop will run forever, causing the program and device to crash!</li>"
        "</ol>"
        "<h3>🎮 Loop Control Statements:</h3>"
        "<ul>"
        "<li><b>The <code>break</code> Statement:</b> Stop and exit the loop immediately, even if the main while condition is still true.</li>"
        "<li><b>The <code>continue</code> Statement:</b> Stop the current iteration of the loop, skip the remaining lines, and jump directly to the next iteration.</li>"
        "<li><b>The <code>else</code> Statement:</b> Run a block of code exactly once when the loop condition becomes false.</li>"
        "</ul>"
    ),
    6: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>For Loops (Iterating over collections)</li>"
        "<li>Looping through Strings (Characters sequence)</li>"
        "<li>The <code>range()</code> Function & its Parameters</li>"
        "<li>Break and Continue inside For Loops</li>"
        "<li>The Else Block in For Loops</li>"
        "<li>Nested Loops (Grid & 2D coordinates design)</li>"
        "</ul>"
        "<hr>"
        "<h3>🔄 For Loops in Python</h3>"
        "A for loop is used for iterating over a sequence (such as a list, a tuple, a dictionary, a set, or a text string)."
        "<h3>🔤 Looping Through a String:</h3>"
        "Even strings are iterable objects! They contain a ordered sequence of characters.<br>"
        "<b>Example:</b><br>"
        "<code>for letter in \"banana\":</code><br>"
        "<code>    print(letter)</code><br>"
        "This will loop through and print each character: <code>b</code>, <code>a</code>, <code>n</code>, <code>a</code>, <code>n</code>, <code>a</code>."
        "<h3>📐 The <code>range()</code> Function</h3>"
        "To loop through a set of code a specified number of times, we use the built-in <code>range()</code> function. It returns a sequence of numbers, starting from 0 by default, increments by 1 by default, and stops before a specified number."
        "<ul>"
        "<li><code>range(6)</code>: Generates numbers 0, 1, 2, 3, 4, 5.</li>"
        "<li><code>range(2, 6)</code>: Specifying a start value: 2, 3, 4, 5.</li>"
        "<li><code>range(2, 30, 3)</code>: Specifying a custom step size of 3: 2, 5, 8, 11, 14, 17, 20, 23, 26, 29.</li>"
        "</ul>"
        "<h3>🎮 Loop Control in For:</h3>"
        "<ul>"
        "<li><b><code>break</code>:</b> Stops the loop before it has completed all items.</li>"
        "<li><b><code>continue</code>:</b> Stops the current iteration, skipping to the next element.</li>"
        "<li><b><code>else</code> in For Loop:</b> Specifies a block of code to run when the loop has finished successfully. <i>Note:</i> The else block will NOT execute if the loop is stopped by a <code>break</code> statement.</li>"
        "</ul>"
        "<h3>🌀 Nested Loops</h3>"
        "A nested loop is a loop inside a loop. The \"inner loop\" will be executed completely one time for each single iteration of the \"outer loop\". This is extremely useful for drawing 2D coordinates, grids, matrices, and tables!<br>"
        "<b>Example:</b><br>"
        "<code>adj = [\"red\", \"big\"]</code><br>"
        "<code>fruits = [\"apple\", \"banana\"]</code><br>"
        "<code>for x in adj:</code><br>"
        "<code>    for y in fruits:</code><br>"
        "<code>        print(x, y)</code>"
    ),
    7: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>Introduction to Functions</li>"
        "<li>Pre-defined (Built-in) vs User-defined Functions</li>"
        "<li>Creating and Calling Functions using <code>def</code></li>"
        "<li>Function Indentation Scope</li>"
        "<li>Arguments vs Parameters</li>"
        "<li>The <code>return</code> Statement</li>"
        "<li>Arbitrary Arguments (<code>*args</code>)</li>"
        "<li>Default Parameter Values</li>"
        "</ul>"
        "<hr>"
        "<h3>⚙️ Functions in Python</h3>"
        "A function is an organized, reusable block of code that only runs when it is called. You can pass data (Parameters) into a function, and the function can return data (Result) as a output."
        "<h3>🛠️ Pre-defined vs User-defined Functions:</h3>"
        "<ul>"
        "<li><b>Pre-defined Functions:</b> Functions that are built into Python, ready for us to use directly (e.g., <code>print()</code>, <code>input()</code>, <code>len()</code>, <code>type()</code>, <code>int()</code>).</li>"
        "<li><b>User-defined Functions:</b> Custom functions that we build from scratch to perform our specific operations!</li>"
        "</ul>"
        "<h3>📝 Creating and Calling a Function:</h3>"
        "<ul>"
        "<li><b>Creating:</b> Defined using the <code>def</code> keyword.<br>"
        "<code>def my_function():</code><br>"
        "<code>    print(\"Hello from inside!\")</code></li>"
        "<li><b>Calling:</b> To call it, use the function name followed by parentheses:<br>"
        "<code>my_function()</code></li>"
        "<li><b>⚠️ Critical Note on Indentation:</b> Python uses indentation (empty spaces at the beginning of lines) to define the body and scope of the function. Any lines belonging to the function must be indented under the <code>def</code> statement!</li>"
        "</ul>"
        "<h3>📥 Parameters vs Arguments:</h3>"
        "Information can be passed to functions through parameters. Although they seem similar, they differ in terms of context:"
        "<ul>"
        "<li><b>Parameter:</b> The variable listed inside the parentheses in the function definition (e.g., <code>def greet(name):</code> - <code>name</code> is the parameter).</li>"
        "<li><b>Argument:</b> The actual value sent to the function when it is called (e.g., <code>greet(\"Youssef\")</code> - <code>\"Youssef\"</code> is the argument).</li>"
        "</ul>"
        "<h3>📤 The <code>return</code> Statement:</h3>"
        "To allow a function to compute and return a result back to the caller, use the <code>return</code> keyword inside the function body."
        "<h3>🌟 Advanced Parameters:</h3>"
        "<ul>"
        "<li><b>Arbitrary Arguments (<code>*args</code>):</b> If you do not know beforehand how many arguments will be passed into your function, add an asterisk (<code>*</code>) before the parameter name. The function will receive a tuple of arguments!</li>"
        "<li><b>Default Parameter Value:</b> If we call the function without an argument, it automatically uses its predefined default value (e.g., <code>def my_func(country = \"Norway\"):</code>).</li>"
        "</ul>"
    ),
    8: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>What is a Python Library?</li>"
        "<li>Finding and Installing Libraries via `pypi.org`</li>"
        "<li>How to use `pip` in Anaconda or Command Prompt</li>"
        "<li>Introduction to the Interactive Turtle Drawing Library</li>"
        "<li>Common Turtle Methods (Drawing Shapes and Colors)</li>"
        "<li>Understanding Axes (X, Y) and Quadrants in Turtle</li>"
        "<li>Using Loops in Turtle Drawing</li>"
        "<li>Converting Python Scripts (<code>.py</code>) to standalone Executable (<code>.exe</code>) files</li>"
        "</ul>"
        "<hr>"
        "<h3>📚 Python Libraries</h3>"
        "A library is a pre-written collection of utility methods, classes, and modules that your application code can import and use to perform complex, specific tasks without writing the code from scratch! Python libraries exist for all major fields, including Machine Learning, Data Science, Visualizations, Game Development, and Web Services."
        "<h3>📥 How to Install External Libraries:</h3>"
        "<ol>"
        "<li>Go to PyPI: <a href='https://pypi.org/' target='_blank'>pypi.org</a>, the official repository for Python packages.</li>"
        "<li>Search for the needed library and copy the pip install command (e.g., <code>pip install library_name</code>).</li>"
        "<li>Open your command prompt or Anaconda prompt. Make sure pip is ready: <code>python -m ensurepip</code>.</li>"
        "<li>Paste and run the copied installation command to download and install the package.</li>"
        "</ol>"
        "<h3>🐢 The Turtle Drawing Board</h3>"
        "The <code>turtle</code> library is a built-in Python feature that provides a virtual drawing board. We can program a turtle object to move on the board and draw amazing shapes and colorful geometric patterns."
        "<h3>🛠️ Commonly Used Turtle Methods:</h3>"
        "<ul>"
        "<li><code>forward(dist)</code> / <code>backward(dist)</code>: Move the turtle forward/backward by a specific distance.</li>"
        "<li><code>right(angle)</code> / <code>left(angle)</code>: Turn the turtle right/left by a specific degree angle.</li>"
        "<li><code>penup()</code> / <code>pendown()</code>: Lift/lower the pen. Lift it to move without drawing lines!</li>"
        "<li><code>color(color_name)</code>: Set drawing and fill colors (supports standard names from trinket colors: <a href='https://trinket.io/docs/colors' target='_blank'>trinket.io/docs/colors</a>).</li>"
        "<li><code>begin_fill()</code> / <code>end_fill()</code>: Call before and after drawing a closed shape to fill it with color!</li>"
        "<li><code>circle(radius)</code>: Draws a circle with a specified radius.</li>"
        "<li><code>exitonclick()</code>: Keeps the drawing window open until the user clicks on it to close.</li>"
        "</ul>"
        "<h3>📐 Understanding the Drawing Coordinates:</h3>"
        "Turtle operates on two main axes: <b>X (horizontal)</b> and <b>Y (vertical)</b>, divided into 4 quadrants. The center of the screen starts at coordinates <code>(0,0)</code>."
        "<h3>🔄 Using Loops in Turtle:</h3>"
        "We can combine loops with turtle commands to easily repeat lines (e.g., drawing a square by repeating forward and turn 4 times). Tip: Use the underscore <code>_</code> as a loop counter variable if it is not referenced inside the loop body."
        "<h3>📦 Packaging Python files to <code>.exe</code>:</h3>"
        "You can easily pack your code into a standalone executable file that opens directly on any computer without needing Python installed, using <b>auto-py-to-exe</b>:"
        "<ul>"
        "<li>Install tool: <code>pip install auto-py-to-exe</code></li>"
        "<li>Open tool: <code>python -m auto_py_to_exe</code></li>"
        "<li>Steps: Select the file location, choose \"One File\" option, select output directory, and click convert!</li>"
        "</ul>"
    ),
    9: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>Object-Oriented Programming (OOP) Concepts</li>"
        "<li>Classes (The Blueprint/Cookie cutter) vs Objects (Instances)</li>"
        "<li>The Constructor Method (<code>__init__</code>)</li>"
        "<li>The <code>self</code> Parameter & why it is essential</li>"
        "<li>Calling methods and variables inside Classes</li>"
        "<li>Using Formatted Strings (<code>f\"\"</code>) in OOP</li>"
        "</ul>"
        "<hr>"
        "<h3>🧬 Object-Oriented Programming (OOP)</h3>"
        "OOP is a programming approach to organizing code just like real-world entities. It allows us to bundle properties (attributes) and behaviors (methods/functions) inside organized structures."
        "<h3>🧱 Classes vs Objects:</h3>"
        "<ul>"
        "<li><b>Class:</b> The general blueprint, template, or cookie cutter. It defines what attributes and methods the spawned object will have.</li>"
        "<li><b>Object:</b> The real instance created from the class template. E.g., if \"Person\" is the Class, then \"Youssef\" is the Object, having a unique age and name!</li>"
        "</ul>"
        "<h3>🎬 The Constructor Method (<code>__init__</code>):</h3>"
        "The <code>__init__</code> method is a special constructor function in Python classes. Python calls it automatically whenever we initialize or spawn a new object. It is used to initialize the object's attributes and set up its default state."
        "<h3>🔮 The <code>self</code> Parameter:</h3>"
        "<ul>"
        "<li>The <code>self</code> parameter represents the current instance of the class object we are currently working with (similar to <code>this</code> pointer in other languages).</li>"
        "<li>It is obligatory and must be the <b>first parameter</b> in any function or method definition we write inside the class.</li>"
        "<li>To access any variable or call another method inside the class body, you must prefix it with <code>self</code> (e.g., <code>self.name</code> or <code>self.greet()</code>).</li>"
        "</ul>"
        "<h3>🔤 Formatted Strings in OOP:</h3>"
        "Inside class methods, we use formatted strings <code>f\"Hello {self.name}\"</code> to easily and cleanly embed object attributes inside our printed statements!"
    ),
    10: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>What is a Brute Force Attack?</li>"
        "<li>Dictionary Attack vs Simple Brute Force</li>"
        "<li>The <code>requests</code> Library for Automated Web Audits</li>"
        "<li>The <code>sys</code> Library for System Integration & Exits</li>"
        "<li>Front-End vs Back-End Web Concepts</li>"
        "<li>Flask Web Framework (Setup, Routing, Server protection)</li>"
        "<li>Building a secure hacking laboratory</li>"
        "</ul>"
        "<hr>"
        "<h3>💻 Hacking and Cybersecurity Lab</h3>"
        "In this station, we build an ethical hacking lab to understand how cyber threats operate so we can defend our servers."
        "<h3>🔓 What is a Brute Force Attack?</h3>"
        "A Brute Force Attack is a trial-and-error method where an automated script systematically attempts every possible password combination until it cracks the correct one."
        "<ul>"
        "<li><b>Simple Brute Force:</b> The script generates random characters sequentially (e.g., trying a, b, c, aa, ab...).</li>"
        "<li><b>Dictionary Attack:</b> The script tries a pre-compiled wordlist file containing hundreds of thousands of common real-world passwords (e.g., <code>top-100.txt</code> or <code>wordlist.txt</code>). Writing Python scripts to automate this is extremely effective!</li>"
        "</ul>"
        "<h3>🌐 The <code>requests</code> Library</h3>"
        "The <code>requests</code> library is a powerful tool used for sending all standard HTTP requests (GET, POST, PUT, DELETE) to web servers. In cybersecurity, it is used to automate logging in by repeatedly sending username-password payloads to the target form."
        "<h3>⚙️ The <code>sys</code> Library</h3>"
        "The <code>sys</code> library provides functions and parameters to interact with the Python interpreter and operating system environment. In security scripts, it is useful for:"
        "<ol>"
        "<li>Parsing command-line parameters (e.g., setting the target website or payload path).</li>"
        "<li>Terminating and exiting scripts immediately using <code>sys.exit()</code> upon detecting successful credentials.</li>"
        "<li>Redirecting input and output.</li>"
        "</ol>"
        "<h3>🌐 Front-End vs Back-End:</h3>"
        "<ul>"
        "<li><b>Front-End:</b> What the user sees on-screen (HTML forms, CSS buttons, JS effects).</li>"
        "<li><b>Back-End:</b> The server side containing data files, authentication logic, and databases.</li>"
        "</ul>"
        "<h3>🧪 Flask Web Framework</h3>"
        "Flask is a lightweight and powerful micro web framework written in Python, perfect for creating fast web apps, backend APIs, and web services."
        "<ul>"
        "<li><b>Why Flask?</b> It is simple and lightweight, flexible, supports backend routing easily, integrates seamlessly with databases, and is highly extensible!</li>"
        "<li><b>Security Protection:</b> We can write custom rules, log IP addresses, or block excessive incorrect attempts to prevent brute force attacks on our servers!</li>"
        "</ul>"
    ),
    11: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>Introduction to Ping Pong Classic Game Project</li>"
        "<li>Comprehensive Game Architecture & Development Steps</li>"
        "<li>Step 1: Setting up the Screen, Window & Game Loop</li>"
        "<li>Step 2: Initializing Game Objects (Paddles, Ball, Center line, Scoreboard)</li>"
        "<li>Exploring Classic game repositories using `freegames`</li>"
        "</ul>"
        "<hr>"
        "<h3>🏓 Ping Pong Game - Part 1</h3>"
        "We are starting the development of our biggest and most exciting project: building a classic Table Tennis (Ping Pong) game from scratch in Python!"
        "<h3>📋 Comprehensive Game Architecture (The 4 Steps):</h3>"
        "<ol>"
        "<li><b>Setup Window & Game Loop:</b> Create a window, set dimensions, set a dark retro background, and configure manual updates.</li>"
        "<li><b>Setup Game Objects:</b> Initialize and place the game elements (Player 1 paddle, Player 2 paddle, ball, center dotted line, and score labels).</li>"
        "<li><b>Key Bindings and Player Movement:</b> Program player functions and associate keyboard keys to move paddles up and down.</li>"
        "<li><b>Game Loop and Physics:</b> Handle constant ball movement, bounce physics when hitting borders, paddle impact reactions, and updating scores.</li>"
        "</ol>"
        "<h3>🛠️ Step 1: Setting up Window & Loop:</h3>"
        "We configure the main drawing window. We use the turtle method <code>tracer(0)</code> which completely disables default animations. This is a pro technique that allows us to update the screen manually in a while loop, providing super smooth rendering without delay!"
        "<h3>🧱 Step 2: Creating Game Objects:</h3>"
        "We create separate turtle sprites representing:"
        "<ul>"
        "<li><b>Paddles A & B:</b> White rectangular boxes positioned on the far left and far right sides.</li>"
        "<li><b>Ball:</b> A circle positioned in the middle coordinates <code>(0,0)</code>.</li>"
        "<li><b>Center Line:</b> A dashed dividing line drawn down the middle.</li>"
        "<li><b>Score Label:</b> A text board showing Player A: 0 | Player B: 0 using turtle writing.</li>"
        "</ul>"
        "<h3>🎒 Fun Practice with `freegames`:</h3>"
        "You can explore open-source classic Python games using the <code>freegames</code> library. Install it with: <code>pip install freegames</code> and run any classic game (like <code>python -m freegames.snake</code>) to study how its game loops are built!"
    ),
    12: (
        "<h3>🎯 Session Agenda:</h3>"
        "<ul>"
        "<li>Step 3: Key Bindings and Paddle Movement Functions</li>"
        "<li>Step 4: Continuous Ball Movement & Screen Boundaries Collisions</li>"
        "<li>Step 5: Physics of Ball Collisions with Player Paddles</li>"
        "<li>Step 6: Scoring System, Resets & Updating Score labels</li>"
        "<li>Packaging and Compiling complete Python projects to standalone executable files</li>"
        "</ul>"
        "<hr>"
        "<h3>🏆 Ping Pong Game - Part 2</h3>"
        "Welcome to the grand finale! We complete our Ping Pong game by building the interactive physics engine and the scoreboard logic."
        "<h3>🕹️ Step 3: Key Bindings and Player Control:</h3>"
        "We define movement functions for Player A and Player B. For example, moving a paddle up increases its Y coordinate:<br>"
        "<code>def paddle_a_up():</code><br>"
        "<code>    y = paddle_a.ycor()</code><br>"
        "<code>    paddle_a.sety(y + 20)</code><br>"
        "We bind these functions to keyboard buttons (e.g., 'W' / 'S' keys for Player A, Arrow Up / Arrow Down keys for Player B) using <code>screen.onkeypress(func, key)</code> and listen with <code>screen.listen()</code>."
        "<h3>⚽ Step 4: Ball Continuous Movement & Wall Collisions:</h3>"
        "We give our ball movement multipliers: <code>ball.dx = 2</code> (horizontal speed) and <code>ball.dy = 2</code> (vertical speed). In the main loop, the ball updates coordinates constantly:<br>"
        "<code>ball.setx(ball.xcor() + ball.dx)</code><br>"
        "<code>ball.sety(ball.ycor() + ball.dy)</code>"
        "<ul>"
        "<li><b>Top & Bottom Boundaries Collision:</b> If the ball hits the top wall (Y &gt; 290) or bottom wall (Y &lt; -290), we reverse its vertical speed direction: <code>ball.dy *= -1</code> to make it bounce!</li>"
        "</ul>"
        "<h3>⚔️ Step 5: Paddle Collision Physics:</h3>"
        "We check if the coordinates of the ball align with the paddle's face. If the ball enters the paddle's X-range and falls within its Y-span, a collision is registered! We instantly reverse its horizontal direction: <code>ball.dx *= -1</code>, bouncing it back with speed!"
        "<h3>📊 Step 6: Scoring and Resets:</h3>"
        "<ul>"
        "<li>If the ball crosses the right boundary (Player B misses), Player A scores!</li>"
        "<li>If the ball crosses the left boundary (Player A misses), Player B scores!</li>"
        "<li>We reset the ball to the center <code>(0,0)</code>, reverse its initial horizontal direction to serve, and update the text on the scoreboard!</li>"
        "</ul>"
        "<h3>🎉 Project Completion & Packaging:</h3>"
        "Congratulations on completing the path! You can compile your final game script into a single executable using the <b>auto-py-to-exe</b> tool (run <code>python -m auto_py_to_exe</code>). Share the <code>.exe</code> file directly with your friends and family so they can play and celebrate your genius! 🚀🏆"
    )
}

# Update each station's story in the JSON structure
for station in data['stations']:
    s_id = station['id']
    if s_id in stories:
        station['story'] = stories[s_id]

# Save the updated games.json
with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Enrichment completed successfully! games.json has been fully updated.")
